//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Izlaz
    {
        public int ID_Izlaz { get; set; }
        public string Registracioni_Broj { get; set; }
        public System.TimeSpan Vreme_Izlaska { get; set; }
    }
}
