//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnik
    {
        public int ID_Korisnika { get; set; }
        public string Korisnicko_Ime { get; set; }
        public string Ime_Prezime { get; set; }
        public string Pozicija { get; set; }
        public string Sifra { get; set; }
    }
}
